### PR TITLE
Add eyes to the dude

### PR DESCRIPTION
**Pull request by Flying-Toast**

### CODE REVIEW

**Comment by yvnat** [comment]
No. As this is a CL program, it is inherently accessible to the blind and visually impaired through TTS programs. We would like to show off this inclusiveness, and have therefore explicitly drawn the "dude" without eyes.

**Comment by Flying-Toast** [comment]
Just because a person has eyes does not mean they cannot be blind. In fact, most blind people still do have eyes. :eye: :eye:

**Comment by yvnat** [comment]
Dear Flying Toast,

Please understand that the lack of eyes is symbolic and not meant to (necessarily) represent a physical lack of eyes.

Thank you for your understanding,
yvnat and the WWW team

**Comment by Flying-Toast** [comment]
Do you have eyes?

**Comment by Flying-Toast** [comment]
:eyes:

**Comment by Flying-Toast** [comment]
:eyes:

**Comment by Flying-Toast** [comment]
:eyes:

**Comment by Flying-Toast** [comment]
:eyes:

**Comment by Flying-Toast** [comment]
:eyes:

**Comment by Flying-Toast** [comment]
https://en.wikipedia.org/wiki/Eye :eye:

**Comment by yvnat** [comment]
Dear Flying-Toast,

My possession of eyes or lack thereof is irrelevant to the subject.

Thank you for your understanding, and please cease pursuing this subject,
yvnat and the WWW team

**Comment by Flying-Toast** [comment]
&lt;blink&gt;EYES&lt;/blink&gt;

**Comment by Flying-Toast** [comment]
@torvalds what are your thoughts on the subject?

**Pull request closed without merging**
